exclude: 	['README.md', 'config.rb', 'sass']
name: Helen Tran; Product Designer
description: Helen Tran is a Product Designer working at Shopify. She blogs about her life, technology, management and design.
url: http://helentran.com
gems: 
  - jekyll-feed
  - jekyll-redirect-from
permalink: /:title
future: false